name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
# version upgraded by Marco Rossi, was originally 3.0.9
version: 3.0.10
# upgraded intl by trueblue to 0.19.0
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
